sudo: false
language: java
jdk:
  - oraclejdk8
# workaround for mvn 3.3 from https://odoepner.wordpress.com/2015/02/15/build-java-maven-github-project-on-travis-ci/
before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
  - tar zxvf apache-maven-3.3.3-bin.tar.gz
  - chmod +x apache-maven-3.3.3/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.3
  - export PATH=$PWD/apache-maven-3.3.3/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.3
  - export PATH=$PWD/apache-maven-3.3.3/bin:${PATH}
  - hash -r
script: mvn verify
notifications:
  email:
    recipients:
      - travis-ci.org-gitmine@hohenegger.eu
    on_success: change
    on_failure: always
